version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    labels:
      - "hobby-hoster.enable=true"
      - "hobby-hoster.port=8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'